### ISSUE TITLE
Introduce an option to activate automatic assignment of Machine Identifiers (MID).

### ISSUE THREAD

**Issue by stanislaw** [strictdoc-project/strictdoc#1053]
Use cases for MID:

- Precise Diffs
- Attaching review comments to requirements using their MID as reference, not UID which is more volatile.
- Simplifies handling of some internal data structures because MIDs are always there whereas UIDs can be absent.

---

## Remaining work items

- [x] Enable `ENABLE_MID` option for Document.
- [x] Persist MIDs to SDoc files.
- [x] Display MID in the UI when viewing.  
- [x] Display an auto-generated MID in the UI when creating and editing.
- [ ] https://github.com/strictdoc-project/strictdoc/issues/1543

**Comment by stanislaw** [comment]
Closing in favour of #1081 where the autogeneration of UIDs is handled.

The idea of using ``UID`` AND ``MID`` is still undefined.

**Comment by stanislaw** [comment]
Closed by:

- https://github.com/strictdoc-project/strictdoc/pull/1544
- https://github.com/strictdoc-project/strictdoc/pull/1545
- https://github.com/strictdoc-project/strictdoc/pull/1549
