### ISSUE TITLE
UI: Grammar with non-string types

### ISSUE THREAD

**Issue by stanislaw** [strictdoc-project/strictdoc#1076]
Also editing requirement with non-string grammar types:

- [x] SingleChoice: Allow editing options in the UI using a dropdown menu.
- [x] SingleChoice: Prevent a node/requirement form from being saved if a value is out of range.
- [x] MultipleChoice: Prevent a node/requirement form from being saved if a value is out of range.

```
NotImplementedError: GrammarElementFieldSingleChoice(title = "COVERAGE_SINGLE", options = [2 elements], required = False, _tx_position = 357, _tx_position_end = 440, parent = GrammarElement(...), gef_type = "SingleChoice")
```

This ticket can be done together with https://github.com/strictdoc-project/strictdoc/issues/1022.

The follow-up work: #2230.

**Comment by johanenglund** [comment]
Dropdowns in UI for single and multi choice is given a +1 upvote by me!

**Comment by stanislaw** [comment]
Closing this in favor of only one follow-up issue: https://github.com/strictdoc-project/strictdoc/issues/1076.
