### ISSUE TITLE
Documentation train 2023-Q3

### ISSUE THREAD

**Issue by stanislaw** [strictdoc-project/strictdoc#1209]
Previous train: https://github.com/strictdoc-project/strictdoc/issues/1074.
Next train: https://github.com/strictdoc-project/strictdoc/issues/1318.

---

- [x] For non-programming users, explain how to open a terminal program to execute a command.
- [x] Document the inline links.
- [x] Document undocumented features status.
- [x] Mermaid
- [x] Describe features/limitations better.
- [x] Backlog: Statistics screen: Count TBD/TBC.
- [x] Backlog: Statistics screen: Count requirements status.

**Comment by stanislaw** [comment]
Previous train: https://github.com/strictdoc-project/strictdoc/issues/1074.
