### ISSUE TITLE
Documentation train 2023-Q4

### ISSUE THREAD

**Issue by stanislaw** [strictdoc-project/strictdoc#1318]
Previous train: https://github.com/strictdoc-project/strictdoc/issues/1209.
Next train: https://github.com/strictdoc-project/strictdoc/issues/1562.

---

- [x] Roadmap SVG export.
- [x] Relations/roles
- [x] `if x is None vs if x`
- [x] `foo_` convention for lambdas and short for loops.
- [x] Avoid optional parameters
- [x] `...based on a number of TBD/TBCs found in document` -> update.
- [x] CHANGELOG
- [x] Search / query engine
- [x] Document's `ROOT: True/False`
- [x] Security considerations
- [x] Pickling and security
- [x] `source_root_path`
- [x] mypy and using types where possible
- [x] Machine identifiers (MID).
- [x] Link to LIT/FileCheck article.
