### ISSUE TITLE
2023-Q4: Ongoing requirements work

### ISSUE THREAD

**Issue by stanislaw** [strictdoc-project/strictdoc#1410]
- [x] Progress report SDOC-SSS-49 - flow to L3
- [x] Structuring requirements in documents SDOC-SSS-64 - flow to L3 sdoc format .sdoc file req
- [x] Link requirements together SDOC-SSS-7 - flow to L3 (model and markup and UI)
- [x] Multiple link roles SDOC-SSS-8 -> L3
- [x] Reverse parent links SDOC-SSS-71 -> L3
- [x] Documents with nested sections/chapters structure SDOC-SSS-51 -> L3 trace to recursive section model
- [x] Text formatting capabilities SDOC-SSS-63 - add statement
- [x] Incremental generation of documents SDOC-SRS-2 and neighbours - add statements
- [x] SDOC-SSS-14 link to the same PERF reqs of L3
- [x] SDOC-SSS-31 -> change "web" to "graphical user"
- [x] Command-line interface SDOC-SSS-32 -> L3
- [x] Multiple repositories SDOC-SSS-34 - is this about working with documents from several repositories? In any case, this seems to need to be moved.
- [x] Documents CRUD SDOC-SSS-3 -> L3 (reading already, now need RUD)
- [x] Assembling documents from fragments SDOC-SSS-52 -> L3 (trace + a bckl req in UI that fragments shall be supported)
- [x] Document meta information (UID, version, authors, signatures, etc) SDOC-SSS-53 - L3 (model, markup, UI, editing info, HTML2PDF)
- [x] Document versioning -> L2
- [x] EARS syntax Requirement syntax validation (e.g. EARS) -> L3
- [x] Traceability matrices - SDOC-SSS-28 - flow to L3
- [x] 1000-feet view SDOC-SSS-56 -> L3 Link to traceability browser 
- [x] Compliance matrices SDOC-SSS-48 -> L3
- [x] Web API interface SDOC-SSS-68 -> L3 as backlog
- [x] Requirements data from multiple repositories SDOC-SSS-34 -> L3
- [x]  Change management 
- [x] Strict type-safe grammar SDOC-SSS-55 -> L3 (+ check if textx is stated as a technical constraint)
- [x] Machine-readable format SDOC-SSS-54 - L3 SDoc markup readability
- [x] Excel export/import SDOC-SSS-60 - L3, also CSV
- [x] What to do with Free SDOC-SSS-40 on L3?
- [x] What to do with No indentation SDOC-SRS-23 and Type-safe fields
- [x] L1 intro
- [x] L2 intro
