### ISSUE TITLE
Diff/Changelog screen: Part 2: Stabilization and further extensions

### ISSUE THREAD

**Issue by stanislaw** [strictdoc-project/strictdoc#1503]
- [x] S: Server: Enable Changelog as the second tab of Diff.
- [x] S: `origin/main` vs `HEAD` issue. 
- [x] S: MID-based nodes matching (Document, Section, Requirement). 
- [x] M: Switch Changelog entries to cells.
- [x] S: Blank page instructions text. https://github.com/strictdoc-project/strictdoc/issues/1500
- [x] S: Can JS/Stimulus be used on static HTML pages? Standalone/embedded JS?
- [x] M: Vanilla JS replacement for Diff controller.
- [x] S: Handling changes in COMMENTS using similarity > 0.9. https://github.com/strictdoc-project/strictdoc/pull/1525
- [x] S: When there are no changes, do not print Changes or add a placeholder (screenshot below).
- [x] S: Matching section free text – integration test (screenshot below).
- [x] S: Matching document UID.
- [x] M: Blank page instructions text – Styles. 
- [x] M: Abstract -> Free text.
- [x] UI: Diff: Remove extra dotted line artifact #1499 
- [x] S: Static HTML export: ensure that the links/tabs are working correctly.
- [x] S: Display MID fields.

Above this line, the Diff/Changelog is releasable.

---

<img width="378" alt="Bildschirmfoto 2023-12-21 um 21 24 05" src="https://github.com/strictdoc-project/strictdoc/assets/452547/0b72bfd8-6053-4cab-9009-c46c0255b250">

<img width="1167" alt="Bildschirmfoto 2023-12-24 um 12 09 05" src="https://github.com/strictdoc-project/strictdoc/assets/452547/a9b89ba4-dd87-4b4e-8873-1e7d7bd8c6f0">
