### ISSUE TITLE
UI: Editing arbitrary Nodes, not only Requirement

### ISSUE THREAD

**Issue by stanislaw** [strictdoc-project/strictdoc#1537]
Could be done together with https://github.com/strictdoc-project/strictdoc/issues/1022.

Tasks:

- [x] https://github.com/strictdoc-project/strictdoc/pull/1650
- [x] requirement.py -> node.py
- [x] Requirement -> SDocNode
- [x] EditGrammarForm -> EditGrammarElementForm.
- [x] #1661
- [x] Form to select/add grammar elements.
- [x] + button: include all grammar elements, not just the default Section/Requirement.
- [x] When clicking on "edit node", open a form that corresponds to a given element with all its fields.
- [x] Validation messages for non-requirement nodes: remove "requirement".

Open questions:

- What to do with reserved fields? What if a test case does not have a TITLE?
- `edit_grammar_delete_existing_field` -> why `- TYPE: Parent/File` reappears?
