### ISSUE TITLE
SPDX export: Epic and open questions

### ISSUE THREAD

**Issue by stanislaw** [strictdoc-project/strictdoc#1541]
## Tasks

- [x] Basic integration test.
- [x] Print basic Document, Package, File, Snippet.
- [x] Print basic relationships. 
- [x] SHA256 for File
- [ ] SHA256 for Package
- [ ] SHA256 for Snippet

## Open questions

- [ ] SPDX 3 Python code seems to be missing a validation function.

- [ ] It looks like the Snippet implementation in SPDX 3 is not finished.

```
## Snippet
SPDXID: SPDXRef-SNIPPET
line_range: PositiveIntegerRange(begin=12, end=15)
```

- [ ] SoftwarePurpose enum is missing a type for Requirement. The closest I found is DOCUMENTATION.
Also, the serializer seems to ignore the software_purpose field, and it is not printed in the .spdx file.

- [ ] What are these for in Document? `element` and `root_element`?

```
            element=["DUMMY_ELEMENT(what is this for?)"],
            root_element=["DUMMY_ROOT_ELEMENT(what is this for?)"],
```

- [ ] What is specVersion: 1.2.3? Is that SPDX version?

- [ ] How to verify a requirements package? SHA256 of a complete folder that is given to StrictDoc? Ignore non-sdoc files in that folder?
