### ISSUE TITLE
Traceability Matrix Screen: Small CSS layout tweaks

### ISSUE THREAD

**Issue by stanislaw** [strictdoc-project/strictdoc#1553]
As discussed:

- [ ] Add more white for document background.
- [ ] Add placeholder when a document does not have any traceable nodes (white background).
- [ ] Add gray margin between all documents.
