### ISSUE TITLE
2024-Q1: Documentation train

### ISSUE THREAD

**Issue by stanislaw** [strictdoc-project/strictdoc#1562]
Previous train: https://github.com/strictdoc-project/strictdoc/issues/1318
Next train: https://github.com/strictdoc-project/strictdoc/issues/1756

---

- [x] https://github.com/strictdoc-project/strictdoc/issues/1378
- [x] @sdoc markers missing.
- [x] Release notes: L1 and L2 documents in draft, Roadmap, Design document, Overview of the source files, Traceability matrix, Diff/Changelog screens, HTML2PDF, SPDX.
- [x] High priority for resolution of bugs and inconsistencies.
