### ISSUE TITLE
2024-Q1: Ongoing requirements work

### ISSUE THREAD

**Issue by stanislaw** [strictdoc-project/strictdoc#1563]
- [x] https://github.com/strictdoc-project/strictdoc/pull/1574
- [x] Tool identification (about).
- [x] Buttons to copy text to buffer - JS file.
