### ISSUE TITLE
Epic: UI: Editable fragments

### ISSUE THREAD

**Issue by stanislaw** [strictdoc-project/strictdoc#1698]
- [x] Make SDoc reader recursively parse fragment files.
- [x] UI: Editing a fragment section should write back to a fragment file, not a main document file.
- [ ] UI: Shall display fragments, highlighting their presence along with their sections.
- [ ] UI: "Add fragment" button / form.
- [ ] UI: "Delete fragment" button / form.
- [ ] UI: Moving TOC nodes within fragment, moving TOC nodes in- and outside of the fragment.
- [ ] Pickle-caching of fragment files.
- [ ] Verification of incremental generation.
