### ISSUE TITLE
2024-Q2: Code climate

### ISSUE THREAD

**Issue by stanislaw** [strictdoc-project/strictdoc#1770]
Next: https://github.com/strictdoc-project/strictdoc/issues/1912

---

- [x] Section: Remove `root_section`.
- [x] tasks: mypy: remove all important `--disable...` arguments, enable all checks.
  - [x] https://github.com/strictdoc-project/strictdoc/pull/1784
- [x] https://github.com/strictdoc-project/strictdoc/pull/1825
- [x] https://github.com/strictdoc-project/strictdoc/pull/1832
- [x] Finish the migration from REFS to RELATIONS.
  - [x] https://github.com/strictdoc-project/strictdoc/pull/1821
  - [x] https://github.com/strictdoc-project/strictdoc/pull/1824

**Comment by stanislaw** [comment]
```
tests/end2end/screens/document/create_requirement/_relations/_validations/create_requirement_validate_relation_parent_does_not_exist/test_case.py:56: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
tests/end2end/server.py:144: in __exit__
    raise reason_exception from None
tests/end2end/screens/document/create_requirement/_relations/_validations/create_requirement_validate_relation_parent_does_not_exist/test_case.py:48: in test
    form_edit_requirement.do_open_tab("Relations")
tests/end2end/helpers/form/form.py:57: in do_open_tab
    self.test_case.assert_attribute(
build/tox/py38-check/lib/python3.8/site-packages/seleniumbase/fixtures/base_case.py:7476: in assert_attribute
    self.wait_for_attribute(
build/tox/py38-check/lib/python3.8/site-packages/seleniumbase/fixtures/base_case.py:7455: in wait_for_attribute
    return page_actions.wait_for_attribute(
build/tox/py38-check/lib/python3.8/site-packages/seleniumbase/fixtures/page_actions.py:808: in wait_for_attribute
    timeout_exception(NoSuchAttributeException, message)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

exception = <class 'selenium.common.exceptions.NoSuchAttributeException'>
message = "Expected attribute {active} of element {//*[@data-testid='form-tab-Relations']} was not present after 10 seconds!"

    def timeout_exception(exception, message):
        exc, msg = shared_utils.format_exc(exception, message)
>       raise exc(msg)
E       seleniumbase.common.exceptions.NoSuchAttributeException: Message: 
E        Expected attribute {active} of element {//*[@data-testid='form-tab-Relations']} was not present after 10 seconds!

build/tox/py38-check/lib/python3.8/site-packages/seleniumbase/fixtures/page_actions.py:252: NoSuchAttributeException
----- Latest Logs dir: /Users/runner/work/strictdoc/strictdoc/latest_logs/ -----
=========================== short test summary info ============================
```
