### ISSUE TITLE
Feature: [LINK] from/to a Requirement or other nodes: The web UI implementation.

### ISSUE THREAD

**Issue by stanislaw** [strictdoc-project/strictdoc#1839]
Now that the https://github.com/strictdoc-project/strictdoc/pull/1835 is merged, we can proceed with finishing the same for the editable UI part.

- [x] https://github.com/strictdoc-project/strictdoc/pull/1843
- [x] https://github.com/strictdoc-project/strictdoc/pull/1844
- [x] Let a freetext contain a link to a requirement. Then a web UI user removes that requirement.
  - [x] https://github.com/strictdoc-project/strictdoc/pull/1849 (validates incoming LINKs)
  - [x] Deleting a requirement and the UI confirmation dialog. The dialog should not be shown if a deletion cannot proceed.
- [x] Delete node: validate incoming links to anchors.
- [x] When a node is created, the resulting node table shall have LINKs rendered as `<a>`-links.
- [x] Let a freetext contain a link to a requirement. Then a web UI user changes the UID of that requirement.
- [x] https://github.com/strictdoc-project/strictdoc/issues/1556. BTW: There's a similar situation when a linked-to section is deleted in the UI. With strictdoc 0.0.55 it is currently unhandled. The section is removed, no error is reported, the referreing freetext has a dangling LINK afterwards. Is this known/intended?

```
We have the same potential for inconsistency here:

    Let a freetext contain a link to a requirement. Then a web UI user removes that requirement.
    Let a freetext contain a link to a requirement. Then a web UI user changes the UID of that requirement.

I started to handle it, but am currently stuck on how to handle web dialog interactions:

    On click to requirement -> delete, server sends a http 200 turbo-stream answer "Deleting a requirement is an unrecoverable action". The UI displays this with a sdoc-modal HTML element.
    On click to "Delete Requirement", my validation kicks in server side, detects there's a reference, and causes a http 422 response.
    The modal dialog doesn't go away. How to make it disappear and show the validation error instead?

I can probably figure this out on my own but it will take some time for learning. If you know you could help me out with some pointers.

BTW: There's a similar situation when a linked-to section is deleted in the UI. With strictdoc 0.0.55 it is currently unhandled. The section is removed, no error is reported, the referreing freetext has a dangling LINK afterwards. Is this known/intended?

EDIT: Thinking twice, I think it would probably be better to do the validation before the server sends that "unrecoverable action" warning. Because it doesn't make sense to ask users for confirmation of an action that won't succeed anyway. No idea how to do though, guess I'll have learn something about turbo; never used it before.
```

**Comment by stanislaw** [comment]
> BTW: There's a similar situation when a linked-to section is deleted in the UI. With strictdoc 0.0.55 it is currently unhandled. The section is removed, no error is reported, the referreing freetext has a dangling LINK afterwards. Is this known/intended?

I have reviewed this, and we had a ticket for this already. We just missed to complete this along with the other tickets some time ago: https://github.com/strictdoc-project/strictdoc/issues/1556.

I am working to resolve this together with @mettta.

**Comment by stanislaw** [comment]
Closed with the release: https://github.com/strictdoc-project/strictdoc/releases/tag/0.0.57. Please see the release notes.
