### ISSUE TITLE
Epic: TEXT nodes and FREETEXT-TEXT migration

### ISSUE THREAD

**Issue by mettta** [strictdoc-project/strictdoc#1864]
Must for the release:

- [x] #1863
- [x] Switch FREETEXT to be represented as [TEXT] under the hood.
- [x] https://github.com/strictdoc-project/strictdoc/pull/1879
- [x] https://github.com/strictdoc-project/strictdoc/pull/1875
- [x] #1884
- [x] DTR: filter out text nodes.
- [x] #1892

![image](https://github.com/strictdoc-project/strictdoc/assets/490084/d75de0cb-a5c7-42a4-82f9-7e7e1391f265)

**Comment by stanislaw** [comment]
Closed with the release: https://github.com/strictdoc-project/strictdoc/releases/tag/0.0.57.
