### ISSUE TITLE
2024-Q3/Q4: Documentation train

### ISSUE THREAD

**Issue by stanislaw** [strictdoc-project/strictdoc#1911]
Previous train: https://github.com/strictdoc-project/strictdoc/issues/1756
Next train: https://github.com/strictdoc-project/strictdoc/issues/2067

---

- [x] Note on documents portability, similar concerns as with the C portability.
- [x] DevGuide: Avoid `req`, `buf`, `doc`...
- [x] Backlog: Inline link to Document `[LINK: DOC_UID...]`.
- [x] Backlog: Links to Sections/Requirements/Documents from all `[REQUIREMENT]`'s multiline fields.
- [x] Interfacing with Valispace, ValispacePythonAPI#22
- [x] Feature status summary.
- [x] How long has the StrictDoc project been around? -- Redirect to dev plan.
