### ISSUE TITLE
2024-Q3/Q4: Code climate

### ISSUE THREAD

**Issue by stanislaw** [strictdoc-project/strictdoc#1912]
Previous: https://github.com/strictdoc-project/strictdoc/issues/1770
Next: https://github.com/strictdoc-project/strictdoc/issues/2068

---

- [x] Remove unused `render_free_text()`. https://github.com/strictdoc-project/strictdoc/pull/1924
- [x] https://github.com/strictdoc-project/strictdoc/pull/1927
- [x] https://github.com/strictdoc-project/strictdoc/pull/1955
- [x] `output/cache/` instead of `$TMPDIR`.
- [x] `edit_grammar_add_field_move_up_and_down_save`, https://github.com/strictdoc-project/strictdoc/actions/runs/10244497289/job/28337588222?pr=1932.
- [x] `edit_grammar_move_field_down`, https://github.com/strictdoc-project/strictdoc/actions/runs/10256651383/job/28376187324?pr=1932.
