### ISSUE TITLE
HTML2PDF: Export to PDF

### ISSUE THREAD

**Issue by stanislaw** [strictdoc-project/strictdoc#369]
The ticket is work-in-progress. The work items:

- [x] Export to PDF button the in UI.
- [x] Generate printable HTML without `is_running_on_server` to get rid of JS errors.
- [x] Command-line implementation of export: `strictdoc export --formats pdf ...`.
- [x] E2E test if possible.
- [x] Offload HTML2PDF to a subprocess, to not import Selenium in the server code.

---

The following links demonstrate how `Selenium`, `chromedriver`, and `Google Chrome` can be used for printing HTML pages to PDF files.

- https://github.com/maxvst/python-selenium-chrome-html-to-pdf-converter
- [How to convert webpage into PDF by using Python](https://stackoverflow.com/a/63100814/598057)

Working example:

```py
url = 'file:///tmp/paginate/examples/simple.html'

import base64
import json


def send_devtools(driver, cmd, params={}):
    resource = "/session/%s/chromium/send_command_and_get_result" % driver.session_id
    url = driver.command_executor._url + resource
    body = json.dumps({'cmd': cmd, 'params': params})
    response = driver.command_executor._request('POST', url, body)
    return response.get('value')


def get_pdf_from_html(driver, url, print_options={}, output_file_path="example.pdf"):
    driver.get(url)

    calculated_print_options = {
        'landscape': False,
        'displayHeaderFooter': False,
        'printBackground': True,
        'preferCSSPageSize': True,
    }
    calculated_print_options.update(print_options)
    result = send_devtools(driver, "Page.printToPDF", calculated_print_options)
    data = base64.b64decode(result['data'])
    with open(output_file_path, "wb") as f:
        f.write(data)



# example
from selenium import webdriver
from selenium.webdriver.chrome.options import Options

webdriver_options = Options()
webdriver_options.add_argument("--no-sandbox")
webdriver_options.add_argument('--headless')
webdriver_options.add_argument('--disable-gpu')

chromedriver_exec="./chromedriver"
driver = webdriver.Chrome(chromedriver_exec, options=webdriver_options)
get_pdf_from_html(driver, url)
driver.quit()
```
