### ISSUE TITLE
ReqIF implementation roadmap

### ISSUE THREAD

**Issue by stanislaw** [strictdoc-project/strictdoc#520]
With the basic functionality now in place, here are more advanced features:

## General

- [x] Documentation
  - [x] General overview of ReqIF
  - [x] Stage 1 parser
  - [x] Stage 2 parser
- [x] Parsing Spec Hierarchies.
- [x] How different tools distinguish between section and requirement?
  - [x] `subset26-chapter3.reqif`: each requirement has an enum field '_stype_requirement_kind': '_enumVal_Kind_HEADING' for the sections or '_enumVal_Kind_ORDINARY' for the reqs.
  - [x] StrictDoc "native" parser dedicates a separate spec type for SECTION.
- [x] Some documents do not want auto-generated structure (e.g. `subset26-chapter3.reqif`)
- [x] Parsing Spec Relations (initial, all links are Parent links)
- [x] Parsing special fields
- [x] When the [SUBSET-026-3 v330.doc and similar docs](https://github.com/openETCS/modeling/tree/master/model/subset26/chapter3) are parsed correctly, find real-world examples of ReqIF produced by other tools. (moved to https://github.com/strictdoc-project/reqif/issues/3).

## Tools that are known to produce ReqIF

- Doors by IBM
- Enterprise Architect by SparxSystems
- [ReqIF Studio](https://www.formalmind.com/de/tools/studio/) and its previous version [fmStudio](http://formalmind.com/studio) and potentially related [ProR](https://www.eclipse.org/rmf/pror/)

## subset26-chapter3.reqif (parsing of ReqIF produced by fmStudio)

**Note: all of the above items are related to a very custom implementation of ReqIF by this sample file. The following points are not going to be implemented in StrictDoc at least as of today (April 2022).**

- [x] The document title is the first SpecObject that is also a document title. There seems to be no metadata to distinguish between such a privileged spec object and a normal one.
- [x] Embedded XHTML content of the Tables directly in the multiline fields.
- [x] Table of contents (Section `3.2`) is present in the Word, but it is not exported to the .reqif file. Is this responsibility of the parser to auto-generate it?
- [x] List items that are requirement's sub statements, e.g. for parent req `1.2.3`: `1.2.3.a` and `1.2.3.b`. Example: `3.4.1.2` with `In every balise shall at least be stored:`.
- [x] List items that are bullet points: `3.4.4.1.1.*[1]`, `3.4.4.1.1.*[2]`, ...
- [x] Parsing images

## StrictDoc ("native" ReqIF parser)

- [x] #571

---

## Support of tools

To implement the support of tools, it would be nice to have simple samples produced by these tools as follows:

- A sample of a one empty document.
- A sample of three empty documents.
- A sample of one document with one requirement.
- A sample of one document with several requirements.
- A sample of one document having 3 chapters, each having 2 requirements.
- A sample of one document having 3 requirements that reference each other via a parent link: `C -> B, B -> A`.
- A sample of a document having tables and figures (if applicable).

--- 

## Known issues

- `subset26-chapter3.reqif` seems to have bugs in the ReqIF structure.
  - `_3.2` aka Modification History is a header, but it has a requirement type.
  - `_3.7.1.1` is a requirement, but it has a header type. Plenty of other examples: https://github.com/strictdoc-project/strictdoc/pull/527/files#diff-c83fbab3e59a09b64e04ec2e7cf5ddfe5762d4fd5631f9f74ede28c44beb2955L1637. Including the entirely broken level issue starting from here: https://github.com/strictdoc-project/strictdoc/pull/527/files#diff-c83fbab3e59a09b64e04ec2e7cf5ddfe5762d4fd5631f9f74ede28c44beb2955L109524.

**Comment by michael-hillmann** [comment]
Just a note: as far as I know, Enterprise Architect by SparxSystems didn't support the ReqIF format. It uses its own XML format.

**Comment by stanislaw** [comment]
Closing this large ticket in favor of smaller focused tickets, see https://github.com/strictdoc-project/strictdoc/issues/571.
