### ISSUE TITLE
ReqIF-SDoc: exporting/importing (roundtrip)

### ISSUE THREAD

**Issue by stanislaw** [strictdoc-project/strictdoc#571]
- [x] Basic sections with requirements
- [x] SDoc custom grammars
- [x] `DOCUMENT`s `FREE_TEXT`
- [x] `SECTION`s with FREE_TEXT
- ~~COMPOSITE_REQUIREMENT~~
- [x] How to deal with single vs multiline strings?
  - [x] Use a `if "\n" in` decision for now
- [x] Export parent-child relationships

**Comment by stanislaw** [comment]
Closing this large ticket, as the good 80% have been done over the past two years. The smaller tasks will be handled via focused tasks, for example: https://github.com/strictdoc-project/strictdoc/issues/1358.
